name: Docker Image CI

on:
  push:
    branches: [ "to-Azure" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/webapps-deploy@v2
    
    
