name: Docker Image CI

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App

on:
  push:
    branches: [ "to-Azure" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Utilise la distribution Temurin (recommandée)

      # Construire avec Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests



      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag devops-demo_eni:$(date +%s)

      - name: connect to dockerhub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PWD}}

      - name: push image to dockerHub
        run: docker push Makusu22/devops-demo_eni:latest

  deploy:
    permissions:
      contents: none
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    runs-on: ubuntu-latest

    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_MSDEPLOYSITE }}
          publish-profile: ${{ secrets.AZURE_PUBLISHPROFILE }}
          package: '*.jar'
    
    
